name: ride_share
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  dashed_circular_progress_bar: ^0.0.6
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  iconsax: ^0.0.8
  font_awesome_flutter: ^10.8.0
  google_maps_flutter: ^2.10.0
  location: ^8.0.0
  permission_handler: ^11.3.1
  geolocator: ^13.0.2
  pin_code_fields: ^8.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.



dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  
  assets:
    - assets/icons/
    - assets/images/

 
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic




flutter_assets:
  assets_path:
    - assets/icons/
  output_path: lib/core/constants/generated/
  filename: icons.dart
  field_prefix:
    from: assetsIcons
    to:
  classname: AppIcons
  ignore_comments: true

# flutter_assets:
#   assets_path:
#     - assets/images/
#   output_path: lib/core/constants/generated/
#   filename: images.dart
#   field_prefix:
#     from: assetsImages
#     to:
#   classname: AppImages
#   ignore_comments: true


# flutter_assets:
#   assets_path:
#     - assets/animations/
#   output_path: lib/core/constants/generated/
#   filename: animation.dart
#   field_prefix:
#     from: assetsAnimations
#     to:
#   classname: AppAnimations
#   ignore_comments: true

