// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-lOTwXjRKBXuJBBS9NnTaIQpaxNnXao',
    appId: '1:588461338678:web:1743547e519ffaa3076897',
    messagingSenderId: '588461338678',
    projectId: 'ride-share-9cbc6',
    authDomain: 'ride-share-9cbc6.firebaseapp.com',
    storageBucket: 'ride-share-9cbc6.firebasestorage.app',
    measurementId: 'G-B5K9872E2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDstDw-6ez4Ip-x6qfFNSGJCz8isWe6a40',
    appId: '1:588461338678:android:5ef20d0644340637076897',
    messagingSenderId: '588461338678',
    projectId: 'ride-share-9cbc6',
    storageBucket: 'ride-share-9cbc6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsGCm6tExZKsa32hXM2baCwlgLnyOScMo',
    appId: '1:588461338678:ios:46446d5164831fc1076897',
    messagingSenderId: '588461338678',
    projectId: 'ride-share-9cbc6',
    storageBucket: 'ride-share-9cbc6.firebasestorage.app',
    iosBundleId: 'com.example.rideShare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsGCm6tExZKsa32hXM2baCwlgLnyOScMo',
    appId: '1:588461338678:ios:46446d5164831fc1076897',
    messagingSenderId: '588461338678',
    projectId: 'ride-share-9cbc6',
    storageBucket: 'ride-share-9cbc6.firebasestorage.app',
    iosBundleId: 'com.example.rideShare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE-lOTwXjRKBXuJBBS9NnTaIQpaxNnXao',
    appId: '1:588461338678:web:4dd0d68e13348171076897',
    messagingSenderId: '588461338678',
    projectId: 'ride-share-9cbc6',
    authDomain: 'ride-share-9cbc6.firebaseapp.com',
    storageBucket: 'ride-share-9cbc6.firebasestorage.app',
    measurementId: 'G-3C2W612SJD',
  );
}
